/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author main
 */
package com.mycompany.trekplanner;

import javax.swing.JOptionPane;

public class createtrek extends javax.swing.JFrame {

    /**
     * Creates new form createtrek
     */
    public createtrek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLblcreate_trek = new javax.swing.JLabel();
        jlabitinary = new javax.swing.JLabel();
        jlbheight = new javax.swing.JLabel();
        jlabeltransportation = new javax.swing.JLabel();
        jlabelinfo = new javax.swing.JLabel();
        jlbinclusion = new javax.swing.JLabel();
        itinaryField = new javax.swing.JTextField();
        transportationNameField = new javax.swing.JTextField();
        heightNameField = new javax.swing.JTextField();
        inclusionsNameField = new javax.swing.JTextField();
        infoNameField = new javax.swing.JTextField();
        jlbtrekname = new javax.swing.JLabel();
        jlbprice = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jlblocation1 = new javax.swing.JLabel();
        trekNameField = new javax.swing.JTextField();
        locNameField = new javax.swing.JTextField();
        confirmbutton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        jLblcreate_trek.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLblcreate_trek.setForeground(new java.awt.Color(255, 255, 255));
        jLblcreate_trek.setText("Create Trek");
        jPanel1.add(jLblcreate_trek);
        jLblcreate_trek.setBounds(99, 33, 246, 52);

        jlabitinary.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlabitinary.setForeground(new java.awt.Color(255, 255, 255));
        jlabitinary.setText("short Itinary");
        jPanel1.add(jlabitinary);
        jlabitinary.setBounds(170, 380, 182, 47);

        jlbheight.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbheight.setForeground(new java.awt.Color(255, 255, 255));
        jlbheight.setText("Height");
        jPanel1.add(jlbheight);
        jlbheight.setBounds(170, 240, 182, 47);

        jlabeltransportation.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlabeltransportation.setForeground(new java.awt.Color(255, 255, 255));
        jlabeltransportation.setText("Transportation");
        jPanel1.add(jlabeltransportation);
        jlabeltransportation.setBounds(170, 310, 182, 47);

        jlabelinfo.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlabelinfo.setForeground(new java.awt.Color(255, 255, 255));
        jlabelinfo.setText("Information about trek ");
        jPanel1.add(jlabelinfo);
        jlabelinfo.setBounds(70, 540, 270, 47);

        jlbinclusion.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbinclusion.setForeground(new java.awt.Color(255, 255, 255));
        jlbinclusion.setText("Inclusions");
        jPanel1.add(jlbinclusion);
        jlbinclusion.setBounds(170, 450, 182, 47);

        itinaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itinaryFieldActionPerformed(evt);
            }
        });
        jPanel1.add(itinaryField);
        itinaryField.setBounds(349, 384, 228, 47);

        transportationNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportationNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(transportationNameField);
        transportationNameField.setBounds(349, 312, 228, 47);

        heightNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(heightNameField);
        heightNameField.setBounds(349, 238, 228, 47);

        inclusionsNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inclusionsNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(inclusionsNameField);
        inclusionsNameField.setBounds(349, 456, 228, 49);
        jPanel1.add(infoNameField);
        infoNameField.setBounds(349, 541, 228, 47);

        jlbtrekname.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlbtrekname.setForeground(new java.awt.Color(255, 255, 255));
        jlbtrekname.setText("Name of trek ");
        jPanel1.add(jlbtrekname);
        jlbtrekname.setBounds(160, 100, 182, 47);

        jlbprice.setFont(new java.awt.Font("BankGothic Md BT", 1, 18)); // NOI18N
        jlbprice.setForeground(new java.awt.Color(255, 255, 255));
        jlbprice.setText("price");
        jPanel1.add(jlbprice);
        jlbprice.setBounds(150, 610, 182, 47);

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });
        jPanel1.add(priceField);
        priceField.setBounds(349, 615, 228, 47);

        jlblocation1.setFont(new java.awt.Font("BankGothic Md BT", 0, 18)); // NOI18N
        jlblocation1.setForeground(new java.awt.Color(255, 255, 255));
        jlblocation1.setText("Location");
        jPanel1.add(jlblocation1);
        jlblocation1.setBounds(170, 170, 182, 47);

        trekNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trekNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(trekNameField);
        trekNameField.setBounds(350, 100, 228, 47);

        locNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(locNameField);
        locNameField.setBounds(349, 173, 228, 47);

        confirmbutton.setBackground(new java.awt.Color(102, 102, 102));
        confirmbutton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        confirmbutton.setForeground(new java.awt.Color(255, 255, 255));
        confirmbutton.setText("CONFIRM");
        confirmbutton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        confirmbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmbutton);
        confirmbutton.setBounds(720, 230, 120, 40);

        homeButton.setBackground(new java.awt.Color(102, 102, 102));
        homeButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("HOME");
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(720, 290, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BGpict.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 700);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-4, 0, 1080, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transportationNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportationNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportationNameFieldActionPerformed

    private void heightNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightNameFieldActionPerformed

    private void itinaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itinaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itinaryFieldActionPerformed

    private void trekNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trekNameFieldActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_trekNameFieldActionPerformed

    private void locNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locNameFieldActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        createtrek.this.dispose();
        dashboard_v2 db = new dashboard_v2();
        db.setLocationRelativeTo(null);
        db.setVisible(true);
        
    }//GEN-LAST:event_homeButtonActionPerformed

    private void confirmbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbuttonActionPerformed
        // TODO add your handling code here:
      String enteredName = trekNameField.getText(); 
      String enteredLocation = locNameField.getText();
      String enteredHeight = heightNameField.getText();
      String enteredTransportationName = transportationNameField.getText();
      String enteredItinary = itinaryField.getText();
      String enteredInclusionsName = inclusionsNameField.getText();
      String enteredInfoName = infoNameField.getText();
      String enteredPrice = priceField.getText();
      
      
      TrekData.setTrekname(enteredName);
      TrekData.setLocName(enteredLocation);
      TrekData.setHeightName(enteredHeight);
      TrekData.setTransportationName(enteredTransportationName);
      TrekData.setItinary(enteredItinary);
      TrekData.setinclusionsName(enteredInclusionsName);
      TrekData.setinfoName(enteredInfoName);
      TrekData.setPrice(enteredPrice);
      
      
      String trekName = TrekData.getTrekname();
      String locName = TrekData.getLocName();
      String heightName = TrekData.getHeightName();
      String transportationName = TrekData.getTransportationName();
      String itinary = TrekData.getItinary();
      String inclusionsName = TrekData.getInclusionsName();
      String infoName = TrekData.getinfoName();
      String price = TrekData.getPrice();
      
      DisplayCreateTrek display = new DisplayCreateTrek();
      DisplayCreateTrek.trekNameDisplayLabel.setText("Name of Trek : " + trekName);
      DisplayCreateTrek.locNameDisplayLabel.setText("Location of trek : " + locName );
      DisplayCreateTrek.heightNameDisplayLabel.setText("Height : " + heightName);
      DisplayCreateTrek.transportationNameDisplayLabel.setText("Transportation : " + transportationName);
      DisplayCreateTrek.itinaryDisplayLabel.setText("Short Itiary : " + itinary);
      DisplayCreateTrek.inclusionsNameDisplayLabel.setText("Inclusions : " + inclusionsName);
      DisplayCreateTrek.infoNameDisplayLabel.setText("Information about Trek : " + infoName);
      DisplayCreateTrek.priceDisplayLabel.setText("Price : " + price);
      
      display.setLocationRelativeTo(null);
      display.setVisible(true);
      
      
      
      
    }//GEN-LAST:event_confirmbuttonActionPerformed

    private void inclusionsNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inclusionsNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inclusionsNameFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmbutton;
    private javax.swing.JTextField heightNameField;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField inclusionsNameField;
    private javax.swing.JTextField infoNameField;
    private javax.swing.JTextField itinaryField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblcreate_trek;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlabelinfo;
    private javax.swing.JLabel jlabeltransportation;
    private javax.swing.JLabel jlabitinary;
    private javax.swing.JLabel jlbheight;
    private javax.swing.JLabel jlbinclusion;
    private javax.swing.JLabel jlblocation1;
    private javax.swing.JLabel jlbprice;
    private javax.swing.JLabel jlbtrekname;
    private javax.swing.JTextField locNameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField transportationNameField;
    private javax.swing.JTextField trekNameField;
    // End of variables declaration//GEN-END:variables
}
