/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trekplanner;

/**
 *
 * @author ADMIN
 */
public class dashboard_v2 extends javax.swing.JFrame {

    /**
     * Creates new form dashboard_v2
     */
    public dashboard_v2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardframe = new javax.swing.JPanel();
        db_treklabel2 = new javax.swing.JLabel();
        db_plannerlabel2 = new javax.swing.JLabel();
        treklabel1 = new javax.swing.JLabel();
        create_trek_button = new javax.swing.JButton();
        my_profile_button = new javax.swing.JButton();
        join_trek_button = new javax.swing.JButton();
        db_bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dashboard");
        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(1080, 720));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("dashboard"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardframe.setMaximumSize(new java.awt.Dimension(1080, 720));
        dashboardframe.setMinimumSize(new java.awt.Dimension(1080, 720));
        dashboardframe.setPreferredSize(new java.awt.Dimension(1080, 720));
        dashboardframe.setLayout(null);

        db_treklabel2.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        db_treklabel2.setText("DASHBOARD");
        dashboardframe.add(db_treklabel2);
        db_treklabel2.setBounds(20, 10, 149, 45);

        db_plannerlabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        db_plannerlabel2.setText("PLANNER");
        dashboardframe.add(db_plannerlabel2);
        db_plannerlabel2.setBounds(30, 120, 150, 56);

        treklabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        treklabel1.setText("TREK");
        treklabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        dashboardframe.add(treklabel1);
        treklabel1.setBounds(30, 80, 91, 52);

        create_trek_button.setBackground(new java.awt.Color(204, 255, 255));
        create_trek_button.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        create_trek_button.setText("CREATE A TREK");
        create_trek_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_trek_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_trek_buttonActionPerformed(evt);
            }
        });
        dashboardframe.add(create_trek_button);
        create_trek_button.setBounds(20, 350, 170, 70);

        my_profile_button.setBackground(new java.awt.Color(204, 255, 255));
        my_profile_button.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        my_profile_button.setText("MY PROFILE ");
        my_profile_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        my_profile_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                my_profile_buttonActionPerformed(evt);
            }
        });
        dashboardframe.add(my_profile_button);
        my_profile_button.setBounds(200, 350, 210, 70);

        join_trek_button.setBackground(new java.awt.Color(204, 255, 255));
        join_trek_button.setFont(new java.awt.Font("Swis721 Cn BT", 0, 24)); // NOI18N
        join_trek_button.setText("JOIN A TREK");
        join_trek_button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        join_trek_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                join_trek_buttonActionPerformed(evt);
            }
        });
        dashboardframe.add(join_trek_button);
        join_trek_button.setBounds(420, 350, 190, 70);
        dashboardframe.add(db_bgimage);
        db_bgimage.setBounds(230, 100, 0, 0);

        getContentPane().add(dashboardframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void join_trek_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_join_trek_buttonActionPerformed
        // TODO add your handling code here:
        dashboard_v2.this.dispose();
        createtrekA join_trek = new createtrekA();
        join_trek.setVisible(true);
        
        
    }//GEN-LAST:event_join_trek_buttonActionPerformed

    private void create_trek_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_trek_buttonActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_create_trek_buttonActionPerformed

    private void my_profile_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_my_profile_buttonActionPerformed
        // TODO add your handling code here:
        dashboard_v2.this.dispose();
        profile create_profile = new profile();
        create_profile.setVisible(true);
       
    }//GEN-LAST:event_my_profile_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_trek_button;
    private javax.swing.JPanel dashboardframe;
    private javax.swing.JLabel db_bgimage;
    private javax.swing.JLabel db_plannerlabel2;
    private javax.swing.JLabel db_treklabel2;
    private javax.swing.JButton join_trek_button;
    private javax.swing.JButton my_profile_button;
    private javax.swing.JLabel treklabel1;
    // End of variables declaration//GEN-END:variables
}
