/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trekplanner;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class DisplayCreateTrek extends javax.swing.JFrame {

    /**
     * Creates new form DisplayCreateTrek
     */
    public DisplayCreateTrek() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        trekNameDisplayLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        locNameDisplayLabel = new javax.swing.JLabel();
        heightNameDisplayLabel = new javax.swing.JLabel();
        transportationNameDisplayLabel = new javax.swing.JLabel();
        itinaryDisplayLabel = new javax.swing.JLabel();
        inclusionsNameDisplayLabel = new javax.swing.JLabel();
        infoNameDisplayLabel = new javax.swing.JLabel();
        priceDisplayLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trekNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        trekNameDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        trekNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        trekNameDisplayLabel.setText(" TREK NAME  : ");
        trekNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(trekNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 133, 600, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Your Trek Details : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(395, 395, 395)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1335, -1));

        locNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        locNameDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        locNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        locNameDisplayLabel.setText(" LOCATION : ");
        locNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(locNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 179, 600, 40));

        heightNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        heightNameDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        heightNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        heightNameDisplayLabel.setText(" HEIGHT : ");
        heightNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(heightNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 225, 600, 40));

        transportationNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        transportationNameDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        transportationNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        transportationNameDisplayLabel.setText(" Transportation : ");
        transportationNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(transportationNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 271, 600, 40));

        itinaryDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        itinaryDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        itinaryDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        itinaryDisplayLabel.setText(" Short Itinary : ");
        itinaryDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(itinaryDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 317, 600, 40));

        inclusionsNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        inclusionsNameDisplayLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        inclusionsNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        inclusionsNameDisplayLabel.setText(" Inclusions : ");
        inclusionsNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(inclusionsNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 369, 600, 40));

        infoNameDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        infoNameDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        infoNameDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoNameDisplayLabel.setText(" Information about trek : ");
        infoNameDisplayLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel1.add(infoNameDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 415, 600, 40));

        priceDisplayLabel.setBackground(new java.awt.Color(204, 204, 204));
        priceDisplayLabel.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        priceDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceDisplayLabel.setText(" Price : ");
        priceDisplayLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        jPanel1.add(priceDisplayLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 461, 600, 40));

        confirmButton.setText("CONFIRM AND SEND FOR REVIEW");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 230, 50));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Desktop\\yASH\\TRK_PLANNER_PICS\\a-minimalists-journey-compact-backpack-and-global-compass-atop-a-map-4oku3ll0cpolv5vb.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1340, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1337, 766));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DisplayCreateTrek.this.dispose();
        createtrek ct_menu = new createtrek();
        ct_menu.setLocationRelativeTo(null);
        ct_menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Details sent for Review!! \n You will be reached throrugh email");
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    public static javax.swing.JLabel heightNameDisplayLabel;
    public static javax.swing.JLabel inclusionsNameDisplayLabel;
    public static javax.swing.JLabel infoNameDisplayLabel;
    public static javax.swing.JLabel itinaryDisplayLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel locNameDisplayLabel;
    public static javax.swing.JLabel priceDisplayLabel;
    public static javax.swing.JLabel transportationNameDisplayLabel;
    public static javax.swing.JLabel trekNameDisplayLabel;
    // End of variables declaration//GEN-END:variables
}
